version: "3.9"

services:
    db:
        image: mysql
        container_name: mysql_db
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpMyAdmin_mysql
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 300M

volumes:
    db-data: null
